// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetCareFinalVersion.Models;

namespace PetCareFinalVersion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200204185054_final")]
    partial class final
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PetCareFinalVersion.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<int>("Association_id")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<float>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Association_id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = "10/02/2018 00:00:00",
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Mancha no centro da testa",
                            Image = "/api/animal/img/Napoleão_animal_1.jpg",
                            Name = "Napoleão",
                            Size = "30cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 2,
                            Age = "01/20/2018 00:00:00",
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Cão de pequeno porte",
                            Image = "/api/animal/img/Bolinhas_animal_2.jpg",
                            Name = "Bolinhas",
                            Size = "180 metros",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 150f
                        },
                        new
                        {
                            Id = 3,
                            Age = "05/09/2016 00:00:00",
                            Association_id = 1,
                            Breed = "Boxer",
                            Description = "Muita energia",
                            Image = "/api/animal/img/Bob_animal_3.jpg",
                            Name = "Bob",
                            Size = "1.20m",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 25f
                        },
                        new
                        {
                            Id = 4,
                            Age = "08/17/2017 00:00:00",
                            Association_id = 1,
                            Breed = "Ragdoll",
                            Description = "Pelo longo, com orellahs pretas",
                            Image = "/api/animal/img/Belinha_animal_4.jpg",
                            Name = "Belinha",
                            Size = "25 cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 5,
                            Age = "04/10/2017 00:00:00",
                            Association_id = 2,
                            Breed = "Pastor Alemão",
                            Description = "Dá-se bem com crianças",
                            Image = "/api/animal/img/Duke_animal_5.jpg",
                            Name = "Duke",
                            Size = "50cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 18f
                        },
                        new
                        {
                            Id = 6,
                            Age = "12/03/2016 00:00:00",
                            Association_id = 2,
                            Breed = "Shar-pei",
                            Description = "Gosta de comer comida humida",
                            Image = "/api/animal/img/Grey_animal_6.jpg",
                            Name = "Grey",
                            Size = "50cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 27f
                        },
                        new
                        {
                            Id = 7,
                            Age = "11/10/2019 00:00:00",
                            Association_id = 2,
                            Breed = "Pastor Alemão",
                            Description = "Não gosta de gatos",
                            Image = "/api/animal/img/Leão_animal_7.jpg",
                            Name = "Leão",
                            Size = "15cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 8,
                            Age = "11/27/2019 00:00:00",
                            Association_id = 2,
                            Breed = "Rafeiro",
                            Description = "Perfeito para apartamentos",
                            Image = "/api/animal/img/Faisca_animal_8.jpg",
                            Name = "Faisca",
                            Size = "15cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 1f
                        },
                        new
                        {
                            Id = 9,
                            Age = "05/21/2018 00:00:00",
                            Association_id = 3,
                            Breed = "Rafeiro",
                            Description = "Perfeito para apartamentos",
                            Image = "/api/animal/img/Toby_animal_9.jpg",
                            Name = "Toby",
                            Size = "10cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 10,
                            Age = "03/10/2017 00:00:00",
                            Association_id = 3,
                            Breed = "Rafeiro",
                            Description = "Perfeito para apartamentos",
                            Image = "/api/animal/img/Pipsy_animal_10.jpg",
                            Name = "Pipsy",
                            Size = "20cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 10f
                        },
                        new
                        {
                            Id = 11,
                            Age = "05/11/2018 00:00:00",
                            Association_id = 3,
                            Breed = "Rafeiro",
                            Description = "Não têm pelo",
                            Image = "/api/animal/img/Quirk_animal_11.jpg",
                            Name = "Quirk",
                            Size = "10cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 12,
                            Age = "01/20/2018 00:00:00",
                            Association_id = 3,
                            Breed = "Doberman",
                            Description = "Precisa de muito espaço",
                            Image = "/api/animal/img/Odie_animal_12.jpg",
                            Name = "Odie",
                            Size = "72cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 40f
                        },
                        new
                        {
                            Id = 13,
                            Age = "02/10/2016 00:00:00",
                            Association_id = 4,
                            Breed = "Rafeiro",
                            Description = "Gosta de crianças",
                            Image = "/api/animal/img/Barkley_animal_13.jpg",
                            Name = "Barkley",
                            Size = "50cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 20f
                        },
                        new
                        {
                            Id = 14,
                            Age = "01/15/2017 00:00:00",
                            Association_id = 4,
                            Breed = "Rafeiro",
                            Description = "Não gosta de gato",
                            Image = "/api/animal/img/Maverick_animal_14.jpg",
                            Name = "Maverick",
                            Size = "15cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 10f
                        },
                        new
                        {
                            Id = 15,
                            Age = "02/07/2015 00:00:00",
                            Association_id = 4,
                            Breed = "Rafeiro",
                            Description = "Precisa de muito espaço",
                            Image = "/api/animal/img/Kobe_animal_15.jpg",
                            Name = "Kobe",
                            Size = "40cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 30f
                        },
                        new
                        {
                            Id = 16,
                            Age = "10/02/2019 00:00:00",
                            Association_id = 4,
                            Breed = "Rafeiro",
                            Description = "Gosta de Crianças",
                            Image = "/api/animal/img/Dorito_animal_16.jpg",
                            Name = "Dorito",
                            Size = "20cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 17,
                            Age = "12/29/2017 00:00:00",
                            Association_id = 1,
                            Breed = "Maine Coon",
                            Description = "Precisa de muito espaço",
                            Image = "/api/animal/img/Rage_animal_17.jpg",
                            Name = "Rage",
                            Size = "70cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 5f
                        },
                        new
                        {
                            Id = 18,
                            Age = "01/02/2019 00:00:00",
                            Association_id = 2,
                            Breed = "Rafeiro",
                            Description = "Não gosta de Crianças",
                            Image = "/api/animal/img/Tally_animal_18.jpg",
                            Name = "Tally",
                            Size = "20cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 19,
                            Age = "07/24/2016 00:00:00",
                            Association_id = 3,
                            Breed = "Labrador",
                            Description = "Adora água",
                            Image = "/api/animal/img/Connor_animal_19.jpg",
                            Name = "Connor",
                            Size = "50cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 30f
                        },
                        new
                        {
                            Id = 20,
                            Age = "09/20/2019 00:00:00",
                            Association_id = 4,
                            Breed = "Rafeiro",
                            Description = "bebe",
                            Image = "/api/animal/img/Gaia_animal_20.jpg",
                            Name = "Gaia",
                            Size = "10cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 1f
                        },
                        new
                        {
                            Id = 21,
                            Age = "11/08/2019 00:00:00",
                            Association_id = 1,
                            Breed = "Maine Coon",
                            Description = "Be",
                            Image = "/api/animal/img/Palmer_animal_21.jpg",
                            Name = "Palmer",
                            Size = "5cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 1f
                        },
                        new
                        {
                            Id = 22,
                            Age = "12/29/2018 00:00:00",
                            Association_id = 2,
                            Breed = "Rafeiro",
                            Description = "Gosta de Cães",
                            Image = "/api/animal/img/Warp_animal_22.jpg",
                            Name = "Warp",
                            Size = "15cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 23,
                            Age = "09/13/2019 00:00:00",
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Bom para ter num apartamento",
                            Image = "/api/animal/img/Rave_animal_23.jpg",
                            Name = "Rave",
                            Size = "8cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 1f
                        },
                        new
                        {
                            Id = 24,
                            Age = "11/28/2017 00:00:00",
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Muito energetico",
                            Image = "/api/animal/img/Linus_animal_24.jpg",
                            Name = "Linus",
                            Size = "30cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 5f
                        },
                        new
                        {
                            Id = 25,
                            Age = "08/10/2019 00:00:00",
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Gosta de Cães",
                            Image = "/api/animal/img/Newton_animal_25.jpg",
                            Name = "Newton",
                            Size = "15cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 26,
                            Age = "07/12/2018 00:00:00",
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Desaparecido",
                            Image = "/api/animal/img/Lenny_animal_26.jpg",
                            Name = "Lenny",
                            Size = "10cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 10f
                        },
                        new
                        {
                            Id = 27,
                            Age = "06/28/2018 00:00:00",
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Desaparecido",
                            Image = "/api/animal/img/Lenny_animal_27.jpg",
                            Name = "Lenny",
                            Size = "26cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 10f
                        },
                        new
                        {
                            Id = 28,
                            Age = "02/19/2016 00:00:00",
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Desaparecido",
                            Image = "/api/animal/img/Shakira_animal_28.jpg",
                            Name = "Shakira",
                            Size = "20cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 4f
                        },
                        new
                        {
                            Id = 29,
                            Age = "02/09/2018 00:00:00",
                            Association_id = 2,
                            Breed = "Rafeiro",
                            Description = "Desaparecido",
                            Image = "/api/animal/img/Bagel_animal_29.jpg",
                            Name = "Bagel",
                            Size = "25cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 5f
                        },
                        new
                        {
                            Id = 30,
                            Age = "01/17/2018 00:00:00",
                            Association_id = 2,
                            Breed = "Rafeiro",
                            Description = "Desaparecido",
                            Image = "/api/animal/img/Bingo_animal_30.jpg",
                            Name = "Bingo",
                            Size = "20cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 3f
                        },
                        new
                        {
                            Id = 31,
                            Age = "11/28/2017 00:00:00",
                            Association_id = 2,
                            Breed = "Rafeiro",
                            Description = "Desaparecido",
                            Image = "/api/animal/img/Basil_animal_31.jpg",
                            Name = "Basil",
                            Size = "18cm",
                            Status = "Para adoção",
                            Type = "Gato",
                            Weight = 3f
                        },
                        new
                        {
                            Id = 32,
                            Age = "05/17/2016 00:00:00",
                            Association_id = 3,
                            Breed = "Rafeiro",
                            Description = "Desaparecido",
                            Image = "/api/animal/img/Raisin_animal_32.jpg",
                            Name = "Raisin",
                            Size = "20cm",
                            Status = "Para adoção",
                            Type = "Cão",
                            Weight = 9f
                        });
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Association", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("FoundationDate")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(9) CHARACTER SET utf8mb4")
                        .HasMaxLength(9);

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("Associations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "R. do Matadouro 10, 9050-100 Funchal",
                            Description = "Intervenção Activa na Protecção, Bem-estar e Saúde Animal",
                            FoundationDate = "06/30/1897 00:00:00",
                            Iban = "PT50000702430012359000733",
                            PhoneNumber = "291220852",
                            User_id = 2
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Santa cruz",
                            Description = "A Associação PATA – Porque os Animais Também se Amam",
                            FoundationDate = "05/08/2006 00:00:00",
                            Iban = "233924194",
                            PhoneNumber = "961133214",
                            User_id = 3
                        },
                        new
                        {
                            Id = 3,
                            Adress = "Funchal",
                            Description = "Canil/Gatil Municipal do Funchal que tem como objectivo principal a recolha e alojamento de animais de companhia que se encontrem abandonados",
                            FoundationDate = "02/04/2020 18:50:54",
                            Iban = "28374659",
                            PhoneNumber = "291773357",
                            User_id = 4
                        },
                        new
                        {
                            Id = 4,
                            Adress = "Rua Cidade de Oakland 1 Funchal",
                            Description = "Madeira Animal Welfare tem por objetivo controlar a reprodução de canídeos e felideos abandonados",
                            FoundationDate = "01/02/2012 00:00:00",
                            Iban = "PT50 0007 0000 0008 4526 8682 3",
                            PhoneNumber = "966295555",
                            User_id = 5
                        });
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Association_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateInit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024) CHARACTER SET utf8mb4")
                        .HasMaxLength(1024);

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Association_id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Association_id = 1,
                            DateEnd = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das vacinas",
                            Image = "/api/animal/img/event/event_1.jpg",
                            Location = "No nosso recinto",
                            Price = 25m,
                            Title = "Campanha de Vacinação",
                            Type = ""
                        },
                        new
                        {
                            Id = 2,
                            Association_id = 1,
                            DateEnd = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Concentração Canina",
                            Image = "/api/animal/img/event/event_2.jpg",
                            Location = "Funchal",
                            Price = 30m,
                            Title = "Concentração Canina",
                            Type = ""
                        },
                        new
                        {
                            Id = 3,
                            Association_id = 1,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das vacinas",
                            Image = "/api/animal/img/event/event_3.jpg",
                            Location = "Funchal",
                            Price = 30m,
                            Title = "Campanha de Vacinação",
                            Type = ""
                        },
                        new
                        {
                            Id = 4,
                            Association_id = 2,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das vacinas",
                            Image = "/api/animal/img/event/event_4.jpg",
                            Location = "Santa cruz",
                            Price = 25m,
                            Title = "Campanha de Vacinação",
                            Type = ""
                        },
                        new
                        {
                            Id = 5,
                            Association_id = 2,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das adoções",
                            Image = "/api/animal/img/event/event_8.jpg",
                            Location = "Machico",
                            Price = 25m,
                            Title = "Campanha de adoção",
                            Type = ""
                        },
                        new
                        {
                            Id = 6,
                            Association_id = 3,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mostre o potencial do seu melhor amigo",
                            Image = "/api/animal/img/event/event_6.jpg",
                            Location = "Funchal",
                            Price = 10m,
                            Title = "Concurso Canino",
                            Type = ""
                        },
                        new
                        {
                            Id = 7,
                            Association_id = 4,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das vacinas",
                            Image = "/api/animal/img/event/event_5.jpg",
                            Location = "Santana",
                            Price = 25m,
                            Title = "Campanha de Vacinação",
                            Type = ""
                        },
                        new
                        {
                            Id = 8,
                            Association_id = 4,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das adoções",
                            Image = "/api/animal/img/event/event_7.jpg",
                            Location = "Ribeira Brava",
                            Price = 25m,
                            Title = "Campanha de adoção",
                            Type = ""
                        },
                        new
                        {
                            Id = 9,
                            Association_id = 4,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das vacinas",
                            Image = "/api/animal/img/event/event_9.jpg",
                            Location = "Machico",
                            Price = 25m,
                            Title = "Campanha de Vacinação",
                            Type = ""
                        },
                        new
                        {
                            Id = 10,
                            Association_id = 4,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das adoções",
                            Image = "/api/animal/img/event/event_10.jpg",
                            Location = "Funchal",
                            Price = 25m,
                            Title = "Campanha de adoção",
                            Type = ""
                        });
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.LostAnimalPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024) CHARACTER SET utf8mb4")
                        .HasMaxLength(1024);

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("LostAnimalPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = "291987123",
                            Date = "2020-01-29",
                            Description = "Por favor ajudem me a encontrar a minha cadela numero:925789365",
                            Image = "",
                            Location = "Avenida do mar",
                            Title = "Minha cadelinha desapareceu"
                        },
                        new
                        {
                            Id = 2,
                            Contact = "291987123",
                            Date = "2020-01-15",
                            Description = "Ajude-me a encontar o meu gato numero:925789365",
                            Image = "",
                            Location = "Rua da carreira",
                            Title = "Meu gato encontra-se desaparecido"
                        },
                        new
                        {
                            Id = 3,
                            Contact = "291987123",
                            Date = "2020-01-01",
                            Description = "numero:925789365",
                            Image = "",
                            Location = "Rua das Pretas",
                            Title = "Se alguem ver este cão que me contacte"
                        });
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Association_id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024) CHARACTER SET utf8mb4")
                        .HasMaxLength(1024);

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("Association_id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Association_id = 1,
                            Description = "Ajude a nossa associação a angariar fundos para poder aumentar o espaço",
                            Image = "",
                            Title = "SPAD - Ajude a nossa associação a angariar fundos para poder aumentar o espaço"
                        },
                        new
                        {
                            Id = 2,
                            Association_id = 1,
                            Description = "Ajude a nossa associação doando comida de animal",
                            Image = "",
                            Title = "SPAD - Ajude a nossa associação doando comida de animal"
                        },
                        new
                        {
                            Id = 3,
                            Association_id = 1,
                            Description = "Estamos a ficar sem espaços disponíveis",
                            Image = "",
                            Title = "SPAD - Estamos a ficar sem espaços disponíveis"
                        },
                        new
                        {
                            Id = 4,
                            Association_id = 2,
                            Description = "Numero de animais aumenta no ultimo ano",
                            Image = "",
                            Title = "PATA - Numero de animais aumenta no ultimo ano"
                        },
                        new
                        {
                            Id = 5,
                            Association_id = 2,
                            Description = "Precisamos de doações de ração",
                            Image = "",
                            Title = "PATA - Precisamos de doações de ração"
                        },
                        new
                        {
                            Id = 6,
                            Association_id = 3,
                            Description = "Ano record a nivel de adoção",
                            Image = "",
                            Title = "Ano record a nivel de adoção"
                        },
                        new
                        {
                            Id = 7,
                            Association_id = 3,
                            Description = "Um obrigado a todos os que ajudaram",
                            Image = "",
                            Title = "Um obrigado a todos os que ajudaram"
                        },
                        new
                        {
                            Id = 8,
                            Association_id = 4,
                            Description = "Precismos de doações de ração",
                            Image = "",
                            Title = ""
                        },
                        new
                        {
                            Id = 9,
                            Association_id = 4,
                            Description = "Estamos a ficar sem espaços disponíveis",
                            Image = "",
                            Title = "Estamos a ficar sem espaços disponíveis"
                        },
                        new
                        {
                            Id = 10,
                            Association_id = 4,
                            Description = "Estamos a ficar sem espaços disponíveis",
                            Image = "",
                            Title = "Estamos a ficar sem espaços disponíveis"
                        });
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Admin = true,
                            Email = "Admin@admin.com",
                            Name = "Admin",
                            Password = "$2a$11$zS5qufWsq.RTwLH7Oefih.iWCIPFb.s9hlC1g88ZHjYZCaMxghqi."
                        },
                        new
                        {
                            Id = 2,
                            Admin = false,
                            Email = "spadfnc@gmail.com",
                            Name = "Spad",
                            Password = "$2a$11$uc9suHe0ku.dnMtSUqG1luwKgacIZWj1MwqLkM1e6FSvcuFYacGDq"
                        },
                        new
                        {
                            Id = 3,
                            Admin = false,
                            Email = "pata@pata.pt",
                            Name = "PATA",
                            Password = "$2a$11$I1QVDwlxROOibKNnAs9TBOR1OQBxXIIKsRe5xrr053sE0jNjRWTVS"
                        },
                        new
                        {
                            Id = 4,
                            Admin = false,
                            Email = "CMF@cmf.com",
                            Name = "Canil Municipal do Funchal",
                            Password = "$2a$11$7KY7xvaaTHnfl.HZA.3KnOEn71QdOjGt.BGggBQ8EJ0Gf1cgXmzpy"
                        },
                        new
                        {
                            Id = 5,
                            Admin = false,
                            Email = "amaw@madeiraanimalwelfare.org",
                            Name = "Associação Madeira Animal Welfare",
                            Password = "$2a$11$Uqs2MUrv0XvYMfpjqsyEHOhgSiJinXX45CrHkA/m6Dh1drbzie7Sm"
                        });
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Animal", b =>
                {
                    b.HasOne("PetCareFinalVersion.Models.Association", "Association")
                        .WithMany("Animals")
                        .HasForeignKey("Association_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Association", b =>
                {
                    b.HasOne("PetCareFinalVersion.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Event", b =>
                {
                    b.HasOne("PetCareFinalVersion.Models.Association", "Association")
                        .WithMany("Events")
                        .HasForeignKey("Association_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Post", b =>
                {
                    b.HasOne("PetCareFinalVersion.Models.Association", "Association")
                        .WithMany("Posts")
                        .HasForeignKey("Association_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
