// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetCareFinalVersion.Models;

namespace PetCareFinalVersion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PetCareFinalVersion.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Age")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Association_id")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<float>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Association_id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = new DateTime(2018, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Mancha no centro da testa",
                            Image = "Napoleão_animal_1.jpg",
                            Name = "Napoleão",
                            Personality = "Amoroso",
                            Size = "Médio",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 2,
                            Age = new DateTime(2018, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Bom cão guarda",
                            Image = "Bolinhas_animal_2.jpg",
                            Name = "Bolinhas",
                            Personality = "Calmo",
                            Size = "Grande",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 150f
                        },
                        new
                        {
                            Id = 3,
                            Age = new DateTime(2016, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 1,
                            Breed = "Boxer",
                            Description = "Cão com muita força e energia",
                            Image = "Bob_animal_3.jpg",
                            Name = "Bob",
                            Personality = "Energético",
                            Size = "Grande",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 25f
                        },
                        new
                        {
                            Id = 4,
                            Age = new DateTime(2017, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 1,
                            Breed = "Ragdoll",
                            Description = "Gosta de morder",
                            Image = "Belinha_animal_4.jpg",
                            Name = "Belinha",
                            Personality = "Arisco",
                            Size = "Médio",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 5,
                            Age = new DateTime(2017, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 2,
                            Breed = "Pastor Alemão",
                            Description = "Dá-se bem com crianças",
                            Image = "Duke_animal_5.jpg",
                            Name = "Duke",
                            Personality = "Protector",
                            Size = "Grande",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 18f
                        },
                        new
                        {
                            Id = 6,
                            Age = new DateTime(2016, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 2,
                            Breed = "Shar-pei",
                            Description = "Gosta de comer comida húmida",
                            Image = "Grey_animal_6.jpg",
                            Name = "Grey",
                            Personality = "Calmo",
                            Size = "Médio",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 27f
                        },
                        new
                        {
                            Id = 7,
                            Age = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 2,
                            Breed = "Pastor Alemão",
                            Description = "Não gosta de gatos",
                            Image = "Leão_animal_7.jpg",
                            Name = "Leão",
                            Personality = "Agressivo",
                            Size = "Grande",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 8,
                            Age = new DateTime(2019, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 2,
                            Breed = "Rafeiro",
                            Description = "Perfeito para apartamentos",
                            Image = "Faisca_animal_8.jpg",
                            Name = "Faisca",
                            Personality = "Energético",
                            Size = "Pequeno",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 1f
                        },
                        new
                        {
                            Id = 9,
                            Age = new DateTime(2018, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 3,
                            Breed = "Rafeiro",
                            Description = "Perfeito para apartamentos",
                            Image = "Toby_animal_9.jpg",
                            Name = "Toby",
                            Personality = "Feliz",
                            Size = "Pequeno",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 10,
                            Age = new DateTime(2017, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 3,
                            Breed = "Rafeiro",
                            Description = "Perfeito para apartamentos",
                            Image = "Pipsy_animal_10.jpg",
                            Name = "Pipsy",
                            Personality = "Brincalhão",
                            Size = "Pequeno",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 10f
                        },
                        new
                        {
                            Id = 11,
                            Age = new DateTime(2018, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 3,
                            Breed = "Rafeiro",
                            Description = "Não têm pelo",
                            Image = "Quirk_animal_11.jpg",
                            Name = "Quirk",
                            Personality = "Calmo",
                            Size = "Pequeno",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 12,
                            Age = new DateTime(2018, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 3,
                            Breed = "Doberman",
                            Description = "Precisa de muito espaço",
                            Image = "Odie_animal_12.jpg",
                            Name = "Odie",
                            Personality = "Calmo",
                            Size = "Grande",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 40f
                        },
                        new
                        {
                            Id = 13,
                            Age = new DateTime(2016, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 4,
                            Breed = "Rafeiro",
                            Description = "Gosta de crianças",
                            Image = "Barkley_animal_13.jpg",
                            Name = "Barkley",
                            Personality = "Energético",
                            Size = "Grande",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 20f
                        },
                        new
                        {
                            Id = 14,
                            Age = new DateTime(2017, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 4,
                            Breed = "Rafeiro",
                            Description = "Não gosta de gato",
                            Image = "Maverick_animal_14.jpg",
                            Name = "Maverick",
                            Personality = "Feliz",
                            Size = "Pequeno",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 10f
                        },
                        new
                        {
                            Id = 15,
                            Age = new DateTime(2015, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 4,
                            Breed = "Rafeiro",
                            Description = "Precisa de muito espaço",
                            Image = "Kobe_animal_15.jpg",
                            Name = "Kobe",
                            Personality = "Curioso",
                            Size = "Grande",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 30f
                        },
                        new
                        {
                            Id = 16,
                            Age = new DateTime(2019, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 4,
                            Breed = "Rafeiro",
                            Description = "Gosta de Crianças",
                            Image = "Dorito_animal_16.jpg",
                            Name = "Dorito",
                            Personality = "Feliz",
                            Size = "Pequeno",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 17,
                            Age = new DateTime(2017, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 1,
                            Breed = "Maine Coon",
                            Description = "Precisa de muito espaço",
                            Image = "Rage_animal_17.jpg",
                            Name = "Rage",
                            Personality = "Calmo",
                            Size = "Grande",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 5f
                        },
                        new
                        {
                            Id = 18,
                            Age = new DateTime(2019, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 2,
                            Breed = "Rafeiro",
                            Description = "Não gosta de Crianças",
                            Image = "Tally_animal_18.jpg",
                            Name = "Tally",
                            Personality = "Agressivo",
                            Size = "Pequeno",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 19,
                            Age = new DateTime(2016, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 3,
                            Breed = "Labrador",
                            Description = "Adora água",
                            Image = "Connor_animal_19.jpg",
                            Name = "Connor",
                            Personality = "Brincalhão",
                            Size = "Grande",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 30f
                        },
                        new
                        {
                            Id = 20,
                            Age = new DateTime(2019, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 4,
                            Breed = "Rafeiro",
                            Description = "É muito fofinho.",
                            Image = "Gaia_animal_20.jpg",
                            Name = "Gaia",
                            Personality = "Energético",
                            Size = "Pequeno",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 1f
                        },
                        new
                        {
                            Id = 21,
                            Age = new DateTime(2019, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 1,
                            Breed = "Maine Coon",
                            Description = "Muito bom com crianças.",
                            Image = "Palmer_animal_21.jpg",
                            Name = "Palmer",
                            Personality = "Brincalhão",
                            Size = "Pequeno",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 1f
                        },
                        new
                        {
                            Id = 22,
                            Age = new DateTime(2018, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 2,
                            Breed = "Rafeiro",
                            Description = "Gosta de Cães",
                            Image = "Warp_animal_22.jpg",
                            Name = "Warp",
                            Personality = "Energético",
                            Size = "Pequeno",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 23,
                            Age = new DateTime(2019, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Bom para ter num apartamento",
                            Image = "Rave_animal_23.jpg",
                            Name = "Rave",
                            Personality = "Calmo",
                            Size = "Pequeno",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 1f
                        },
                        new
                        {
                            Id = 24,
                            Age = new DateTime(2017, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Muito energetico",
                            Image = "Linus_animal_24.jpg",
                            Name = "Linus",
                            Personality = "Calmo",
                            Size = "Médio",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 5f
                        },
                        new
                        {
                            Id = 25,
                            Age = new DateTime(2019, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Gosta de Cães",
                            Image = "Newton_animal_25.jpg",
                            Name = "Newton",
                            Personality = "Brincalhão",
                            Size = "Médio",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 2f
                        },
                        new
                        {
                            Id = 26,
                            Age = new DateTime(2018, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Gosta de bolas.",
                            Image = "Lenny_animal_26.jpg",
                            Name = "Lenny",
                            Personality = "Feliz",
                            Size = "Pequeno",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 10f
                        },
                        new
                        {
                            Id = 27,
                            Age = new DateTime(2018, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Gosta de brincar com crianças.",
                            Image = "Lenny_animal_27.jpg",
                            Name = "Lenny",
                            Personality = "Protector",
                            Size = "Médio",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 10f
                        },
                        new
                        {
                            Id = 28,
                            Age = new DateTime(2016, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 1,
                            Breed = "Rafeiro",
                            Description = "Nunca está parado",
                            Image = "Shakira_animal_28.jpg",
                            Name = "Shakira",
                            Personality = "Energético",
                            Size = "Médio",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 4f
                        },
                        new
                        {
                            Id = 29,
                            Age = new DateTime(2018, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 2,
                            Breed = "Rafeiro",
                            Description = "Não gosta de gatos",
                            Image = "Bagel_animal_29.jpg",
                            Name = "Bagel",
                            Personality = "Brincalhão",
                            Size = "Médio",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 5f
                        },
                        new
                        {
                            Id = 30,
                            Age = new DateTime(2018, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 2,
                            Breed = "Rafeiro",
                            Description = "Bom para apartamentos",
                            Image = "Bingo_animal_30.jpg",
                            Name = "Bingo",
                            Personality = "Calmo",
                            Size = "Médio",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 3f
                        },
                        new
                        {
                            Id = 31,
                            Age = new DateTime(2017, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 2,
                            Breed = "Rafeiro",
                            Description = "Adoro apanhar sol",
                            Image = "Basil_animal_31.jpg",
                            Name = "Basil",
                            Personality = "Feliz",
                            Size = "Médio",
                            Status = "Adoção",
                            Type = "Gato",
                            Weight = 3f
                        },
                        new
                        {
                            Id = 32,
                            Age = new DateTime(2016, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Association_id = 3,
                            Breed = "Rafeiro",
                            Description = "Sempre a correr em circulos.",
                            Image = "Raisin_animal_32.jpg",
                            Name = "Raisin",
                            Personality = "Energético",
                            Size = "Médio",
                            Status = "Adoção",
                            Type = "Cão",
                            Weight = 9f
                        });
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Association", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("FoundationDate")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(9) CHARACTER SET utf8mb4")
                        .HasMaxLength(9);

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("Associations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "R. do Matadouro 10, 9050-100 Funchal",
                            Description = "Intervenção Activa na Protecção, Bem-estar e Saúde Animal",
                            FoundationDate = "06/30/1897 00:00:00",
                            Iban = "PT50000702430012359000733",
                            Image = "spad.png",
                            PhoneNumber = "291220852",
                            User_id = 2
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Santa cruz",
                            Description = "A Associação PATA – Porque os Animais Também se Amam",
                            FoundationDate = "05/08/2006 00:00:00",
                            Iban = "PT50000702430012359000733",
                            Image = "PATA.JPG",
                            PhoneNumber = "961133214",
                            User_id = 3
                        },
                        new
                        {
                            Id = 3,
                            Adress = "Funchal",
                            Description = "Canil/Gatil Municipal do Funchal que tem como objectivo principal a recolha e alojamento de animais de companhia que se encontrem abandonados",
                            FoundationDate = "02/06/2020 08:56:42",
                            Iban = "PT50000702430012359000733",
                            Image = "Canil_Municipal_Funchal.jpg",
                            PhoneNumber = "291773357",
                            User_id = 4
                        },
                        new
                        {
                            Id = 4,
                            Adress = "Rua Cidade de Oakland 1 Funchal",
                            Description = "Madeira Animal Welfare tem por objetivo controlar a reprodução de canídeos e felideos abandonados",
                            FoundationDate = "01/02/2012 00:00:00",
                            Iban = "PT50 0007 0000 0008 4526 8682 3",
                            Image = "AMAW.jpg",
                            PhoneNumber = "966295555",
                            User_id = 5
                        });
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Association_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateInit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024) CHARACTER SET utf8mb4")
                        .HasMaxLength(1024);

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Association_id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Association_id = 1,
                            DateEnd = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das vacinas",
                            Image = "event/event_1.jpg",
                            Location = "No nosso recinto",
                            Price = 25m,
                            Title = "Campanha de Vacinação",
                            Type = ""
                        },
                        new
                        {
                            Id = 2,
                            Association_id = 1,
                            DateEnd = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Venha participar nesta Concentração Canina",
                            Image = "event_2.jpg",
                            Location = "Funchal",
                            Price = 30m,
                            Title = "Concentração Canina",
                            Type = ""
                        },
                        new
                        {
                            Id = 3,
                            Association_id = 1,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das vacinas",
                            Image = "event_3.jpg",
                            Location = "Funchal",
                            Price = 30m,
                            Title = "Campanha de Vacinação",
                            Type = ""
                        },
                        new
                        {
                            Id = 4,
                            Association_id = 2,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das vacinas",
                            Image = "event_4.jpg",
                            Location = "Santa cruz",
                            Price = 25m,
                            Title = "Campanha de Vacinação",
                            Type = ""
                        },
                        new
                        {
                            Id = 5,
                            Association_id = 2,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das adoções",
                            Image = "event_8.jpg",
                            Location = "Machico",
                            Price = 25m,
                            Title = "Campanha de adoção",
                            Type = ""
                        },
                        new
                        {
                            Id = 6,
                            Association_id = 3,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mostre o potencial do seu melhor amigo",
                            Image = "event_6.jpg",
                            Location = "Funchal",
                            Price = 10m,
                            Title = "Concurso Canino",
                            Type = ""
                        },
                        new
                        {
                            Id = 7,
                            Association_id = 4,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das vacinas",
                            Image = "event_5.jpg",
                            Location = "Santana",
                            Price = 25m,
                            Title = "Campanha de Vacinação",
                            Type = ""
                        },
                        new
                        {
                            Id = 8,
                            Association_id = 4,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das adoções",
                            Image = "event_7.jpg",
                            Location = "Ribeira Brava",
                            Price = 25m,
                            Title = "Campanha de adoção",
                            Type = ""
                        },
                        new
                        {
                            Id = 9,
                            Association_id = 4,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das vacinas",
                            Image = "event_9.jpg",
                            Location = "Machico",
                            Price = 25m,
                            Title = "Campanha de Vacinação",
                            Type = ""
                        },
                        new
                        {
                            Id = 10,
                            Association_id = 4,
                            DateEnd = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInit = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promoção no preço das adoções",
                            Image = "event_10.jpg",
                            Location = "Funchal",
                            Price = 25m,
                            Title = "Campanha de adoção",
                            Type = ""
                        });
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.LostAnimalPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024) CHARACTER SET utf8mb4")
                        .HasMaxLength(1024);

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("LostAnimalPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = "291987123",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1990),
                            Description = "Por favor ajudem me a encontrar a minha cadela",
                            Image = "lost_1",
                            Location = "Avenida do mar",
                            Title = "Minha cadelinha desapareceu"
                        },
                        new
                        {
                            Id = 2,
                            Contact = "291987123",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2004),
                            Description = "Ajude-me a encontar o meu gato por favor",
                            Image = "lost_2",
                            Location = "Rua da carreira",
                            Title = "Meu gato encontra-se desaparecido"
                        },
                        new
                        {
                            Id = 3,
                            Contact = "291987123",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2018),
                            Description = "É um cão de porte muito grande, mas é amoroso",
                            Image = "lost_3",
                            Location = "Rua das Pretas",
                            Title = "Se alguem ver este cão contacte-me por favor"
                        });
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Association_id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024) CHARACTER SET utf8mb4")
                        .HasMaxLength(1024);

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("Association_id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Association_id = 1,
                            Description = "Queremos pedir ajuda dos nossos sócios e amigos para angariar fundos para aumentar a nossa capacidade abrigar cães",
                            Image = "",
                            Title = "Ajude a nossa associação a angariar fundos para poder aumentar o espaço"
                        },
                        new
                        {
                            Id = 2,
                            Association_id = 1,
                            Description = "Queremos pedir ajuda dos nossos sócios e amigos para angariar comida para os nossos animais.",
                            Image = "",
                            Title = "Ajude a nossa associação doando comida de animal"
                        },
                        new
                        {
                            Id = 3,
                            Association_id = 1,
                            Description = "Viemos por este meio anunciar que estamos completamente sobrelotados.",
                            Image = "",
                            Title = "Estamos a ficar sem espaços disponíveis"
                        },
                        new
                        {
                            Id = 4,
                            Association_id = 2,
                            Description = "Governo Português vem a publico dizer que a taxa de animais abandonados aumentou por 20%.",
                            Image = "",
                            Title = "Numero de animais aumenta no ultimo ano"
                        },
                        new
                        {
                            Id = 5,
                            Association_id = 2,
                            Description = "Queremos pedir ajuda dos nossos sócios e amigos para angariar ração para os nossos animais.",
                            Image = "",
                            Title = "Precisamos de doações de ração"
                        },
                        new
                        {
                            Id = 6,
                            Association_id = 3,
                            Description = "Este ano batemos o record em numero de animais adotados",
                            Image = "",
                            Title = "Ano record a nivel de adoção"
                        },
                        new
                        {
                            Id = 7,
                            Association_id = 3,
                            Description = "Venho por este meio agradeçer a todos pela vossa ajuda.",
                            Image = "",
                            Title = "Um obrigado a todos os que ajudaram"
                        },
                        new
                        {
                            Id = 8,
                            Association_id = 4,
                            Description = "Queremos pedir ajuda dos nossos sócios e amigos para angariar ração para os nossos animais.",
                            Image = "",
                            Title = "Ajude a nossa associação doando comida de animal"
                        },
                        new
                        {
                            Id = 9,
                            Association_id = 4,
                            Description = "Gostariamos de informar que estamos a ficar sem espaço disponível para abrigar mais animais",
                            Image = "",
                            Title = "Estamos a ficar sem espaços disponíveis"
                        },
                        new
                        {
                            Id = 10,
                            Association_id = 4,
                            Description = "Queremos pedir ajuda dos nossos sócios e amigos para angariar ração para os nossos animais.",
                            Image = "",
                            Title = "Precisamos de doações de ração"
                        });
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Admin = true,
                            Email = "Admin@admin.com",
                            Name = "Admin",
                            Password = "$2a$11$wzyd3qcS6MV8rmjOdpnvGemCXM62YXGLz681eOq.Ydu3dwmPkbjzm"
                        },
                        new
                        {
                            Id = 2,
                            Admin = false,
                            Email = "spadfnc@gmail.com",
                            Name = "Spad",
                            Password = "$2a$11$guTR0IuYgYYxHQEo.rKR6e2m9Nhm2xrfn7H2J.lnUQOKLX4H4YPeG"
                        },
                        new
                        {
                            Id = 3,
                            Admin = false,
                            Email = "pata@pata.pt",
                            Name = "PATA",
                            Password = "$2a$11$BEiGRgHgNwZlqMhbXRJu1ePH0sFC78Qkz887AEt/R0rJ8QKgclKOu"
                        },
                        new
                        {
                            Id = 4,
                            Admin = false,
                            Email = "CMF@cmf.com",
                            Name = "Canil Municipal do Funchal",
                            Password = "$2a$11$VQ6Y28yZt4VCOQYyxObn5OuwXONKKzbvqyyB3ZcIOBMiMIIPpPMYa"
                        },
                        new
                        {
                            Id = 5,
                            Admin = false,
                            Email = "amaw@madeiraanimalwelfare.org",
                            Name = "Associação Madeira Animal Welfare",
                            Password = "$2a$11$oNK2YjS8v2uycnpUmL7rHOGOizoFg/Os8cQOFS4LrWou1fHvu/47W"
                        });
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Animal", b =>
                {
                    b.HasOne("PetCareFinalVersion.Models.Association", "Association")
                        .WithMany("Animals")
                        .HasForeignKey("Association_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Association", b =>
                {
                    b.HasOne("PetCareFinalVersion.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Event", b =>
                {
                    b.HasOne("PetCareFinalVersion.Models.Association", "Association")
                        .WithMany("Events")
                        .HasForeignKey("Association_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetCareFinalVersion.Models.Post", b =>
                {
                    b.HasOne("PetCareFinalVersion.Models.Association", "Association")
                        .WithMany("Posts")
                        .HasForeignKey("Association_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
